# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 19:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg', '0001_initial'),
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='planner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='planned_trips', to='login_reg.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='travelers',
            field=models.ManyToManyField(related_name='trips', to='login_reg.User'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='date_from',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='trip',
            name='date_to',
            field=models.CharField(max_length=10),
        ),
    ]
